name: "Github action Test"
on:
  push:
    branches:
      - auth
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      env:
        PRISMA_ENDPOINT: ${{secrets.PRISMA_ENDPOINT}}
        PRISMA_SECRET: ${{secrets.PRISMA_SECRET}}
        API_PORT: ${{API_PORT}}
        DASHBOARD_URL: ${{DASHBOARD_URL}}
        EMAIL: ${{EMAIL}}
        PASSWORD: ${{PASSWORD}}
      
      - uses: actions/checkout@v1
      
      - name: "Install node"
        uses: actions/setup-node@v1
      - name: "Install global packages"
        run: npm i -g mocha yarn

      - name: "up docker-compose file"
        run: docker-compose up -d
      - name: "deploy prisma"
        run: yarn deploy
      - name: "seed database"
        run: yarn seed:db
        
