name: "Github action Test"
on:
  push:
    branches:
      - auth
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: "Install node"
        uses: actions/setup-node@v1
      - name: "Install global packages"
        run: npm i -g mocha yarn prisma-cli
      - name: "install deps"
        run: yarn install
      - name: "up docker-compose file"
        run: docker-compose -f docker-compose.yml up -d
      - name: "deploy prisma"
        run: yarn deploy
      - name: "run test"
        run: yarn test:action
        env:
          PRISMA_ENDPOINT: ${{secrets.PRISMA_ENDPOINT}}
          PRISMA_SECRET: ${{secrets.PRISMA_SECRET}}
          EMAIL: ${{secrets.EMAIL}}
          PASSWORD: ${{secrets.PASSWORD}}
